### ISSUE TITLE
App Lock Not Consistently Operating

### ISSUE THREAD

**Issue by dav1dpgit** [getAlby/lndhub.go#102]
**BW app does not sleep/lock after departing the app from a transaction details screen**

I’ve noticed the app requires a password to re-enter BW if one leaves the app from the top level (wallet summary or all wallet summary) after some short period of time.  However, BW did not require a password to re-enter after a long period of time away if I left BW from the transactions details screen.

I would think you would like these to be consistent.

**Comment by kiwiidb** [comment]
We are not affiliated with Bluewallet. If you have any issues with the Bluewallet app, you could try opening an issue in this repository: https://github.com/BlueWallet/BlueWallet.

**Comment by dav1dpgit** [comment]
Apologies for the mis-post and thanks
