### ISSUE TITLE
404 errors (instead of 400 bad auth errors)

### ISSUE THREAD

**Issue by bumi** [getAlby/lndhub.go#139]
Currently all unknown requests lead to a 400 bad auth error. 
We should make sure that the authentication is only checked for the known routes and have a proper 404 error for unknown routes.

**Comment by skosito** [comment]
@bumi @kiwiidb 
It seems this is behavior of echo https://github.com/labstack/echo/issues/2141#issuecomment-1072270025
Pretty much all groups have these generic route matchers which will map all routes to group if possible and fallback to not found handler. But, secured routes have auth middleware which will be applied before reaching that part of the method.

Flow is in my understanding:
-> non existing route -> matched with generic group with "" prefix that has jwt middleware -> middleware applied -> bad auth returned before not found handler is caught

It says they will remove this in next version. I put a quick and simple solution around this, please take a look if it makes sense and if yes, i will clean it up and create proper PR: https://github.com/getAlby/lndhub.go/pull/143
Alternative is to wait for next version, or maybe go with this solution if it's important and revert when v5 echo is out.

Please let me know your thoughts.

**Comment by kiwiidb** [comment]
Thanks for checking this out. To be honest, I don't know if it is that important to apply such a patch.

**Comment by skosito** [comment]
> Thanks for checking this out. To be honest, I don't know if it is that important to apply such a patch. Maybe we can just wait for the new echo release. Also , a large part of the 404 errors comes from Chrome apparently looking for `ln.getalby.com/favicon.png`, so if we add that we can avoid 404 errors. Also, it might be good to have alerts for 404, then we get a heads up when someone is poking around.

I agree that waiting for new release is better than this, just quickly put it together so alternative solution and limitations are explained a bit better. :) Please let me know next steps here.

**Comment by bumi** [comment]
👍 thought it is something simple. thanks for checking and the proposal

**Comment by bumi** [comment]
I think we are good here now, closing.
