### ISSUE TITLE
Add support for 0-amount incoming invoices

### ISSUE THREAD

**Issue by bumi** [getAlby/lndhub.go#165]
Currently 0-amount invoices are not supported and are not properly settled. 

When the transaction is settled we currently use the invoice.Amount (which is 0): 
https://github.com/getAlby/lndhub.go/blob/feature/webhooks/lib/service/invoicesubscription.go#L85

we should use the amount from the `rawInvoice` there but log if the amount is not the same as the invoice.Amount. 
Maybe we also only do this if the invoice Amount is zero?

**Comment by kiwiidb** [comment]
I would always do it - the payer can be the user themselves and then they should be credited what they sent over in all cases.
