### ISSUE TITLE
Add support for 0-amount outgoing invoices

### ISSUE THREAD

**Issue by bumi** [getAlby/lndhub.go#166]
Currently we do not support paying 0-amount invoices. 

https://github.com/getAlby/lndhub.go/blob/main/controllers/payinvoice.ctrl.go#L74

Note: the balance check needs to be adjusted for that. 
Can the amount be manually set on the `lnPayReq` to leave the rest of the code the same?

**Comment by kiwiidb** [comment]
Fixed by #168
