### ISSUE TITLE
Investigate 3rd party Authorization flows

### ISSUE THREAD

**Issue by kiwiidb** [getAlby/lndhub.go#180]
It should be possible to give an application or service access to your LNDhub account without giving up the full "admin" lndhub connection string. This kind of Authorization could have "create invoice" access, "read transactions" access or "make payment" access with monthly budgets. The Authorization should be time-scoped and a user should be able to have an overview of linked applications and be able to revoke access.

**Comment by kiwiidb** [comment]
An obvious candidate for this authorization flow would be OAuth2. LNDhub.go already uses JWT tokens for Authentication, which integrate well with , and this could be extended for 3rd party Authentication and Authorization. See [this repository](https://github.com/RichardKnop/go-oauth2-server) for a good overview of the protocol and a server implementation in Go. 

The problem with OAuth2 is that it is centralized in the sense that the client app needs to connect using a specific host (Github, Google, Facebook,...). In our case, many wallet providers would be possible and they may be self-hosted by the user. So to initiate the OAuth2 flow, it would be better to use a `lightning` or `lnurl` hyperlink which a user can use with both a mobile wallet or browser-based wallet (Alby). The redirect URL of the OAuth flow would then contain the URL where the client app can go to generate an access token and make API calls.

**Comment by kiwiidb** [comment]
What do you think about this @bumi ?

**Comment by kiwiidb** [comment]
@prusnak Do you mind to share your thoughts on my post above? We would like to get some more opinions on this topic :)

**Comment by prusnak** [comment]
I won't provide my own opinion on this topic as I don't consider myself a well experienced web developer. However, my gut feeling is that your direction in this area is good! 👍

**Comment by prusnak** [comment]
Does it make sense to allow account creation via the 3rd party auth flow?

**Comment by kiwiidb** [comment]
Doesn't really make sense I think since the purpose is to allow a 3rd party to access an existing user's account. The creation endpoint should be open to be called without authentication, unless it's been disabled, right?

**Comment by kiwiidb** [comment]
After a discussion with @bumi I've started to think how we could implement this entire service as a complete stand-alone service / API gateway using https://github.com/go-oauth2/oauth2.



![OAUTH LNDHUB drawio(1)](https://user-images.githubusercontent.com/33457577/175069579-3840d7e6-8fae-4be1-9837-18e5528e9770.png)

- The API from a 3rd party perspective would be the same as described above, allthough it wouldn't be necessary to use JWT tokens for the OAuth2 flow, it could be regular access tokens.
- The OAuth server and API gateway would be incorporated in a single service with a database. The OAuth server is responsible for issueing tokens and the API gateway would be responsible for validating the tokens, checking app permissions and budgets.
- For the authorization call, the OAuth server would authenticate the user using a JWT token (a master token, the same kind as is currently used in LNDhub). It would need access to the JWT secret in order to be able to validate this token.
- The API gateway would generate master tokens on the fly on behalf of the user (it can do this because it has access to the `JWT_SECRET`) and inject them when proxying the request to LNDhub (not that these tokens are never exposed to the 3rd party app).

This architecture would allow us to ship this feature without any changes whatsoever needed to the existing LNDhub codebase, moving everything to a seperate service (and some front-end client work).

**Comment by bumi** [comment]
I like the idea that we can implement this standalone and keep lndhub small and flexible. 

If we implement a permission system (and for that we can use JWT or macaroons) in LNDHub then by default we would also not require an API gateway. (this could be optional) 

The oAuth Server creates access tokens through an API endpoint in LNDHub (authenticated with some admin master user credentials). The 3rd party app then can use those credentials to do calls to LNDHub directly. 

This way the initial authentication can be implemented independently of LNDHub and can also be part of another user-facing app (like for example getalby.com in our case) 

<img width="845" alt="image" src="https://user-images.githubusercontent.com/318/175539706-9305cd9f-568f-45f1-9506-fa906f0c7728.png">

+ 3rd party app initiates the auth flow and redirects the user to a service-auth page
+ user authenticates with service
+ user confirms the permissions
+ service creates a new access tokens though a new LNDHub permissions API (similar to the /auth call currently)
+ service redirects the user to the 3rd party app
+ 3rd party app can acquire the access token
+ 3rd party app can do API calls directly to LNDHub authenticated with the access_token

+ refreshing the token works similar
