### ISSUE TITLE
Fee reservers

### ISSUE THREAD

**Issue by bumi** [getAlby/lndhub.go#182]
Currently we allow users to send 100% of there balance. This means user accounts can go negative because fees are charged after the payment. We can not know the total fees before the payment. 
This is a deliberate choice so far. We value the UX more and eat the fees. It is super annoying for users to see a balance and not know how much they can spend. 

But we should make this configurable and leave it up to the operator if they want to have a fee reserve or not.

**Comment by kiwiidb** [comment]
Duplicate of #183
