### ISSUE TITLE
Go 1.16 vs Go 1.17

### ISSUE THREAD

**Issue by prusnak** [getAlby/lndhub.go#191]
ISTM that go.mod specifies Go 1.17, but the release binaries and the CI are set to using Go 1.16

What's the current support status? Do we aim to support both?

**Comment by kiwiidb** [comment]
We could change the CI and release binaries to 1.17 as well it seems.

**Comment by prusnak** [comment]
> We could change the CI and release binaries to 1.17 as well it seems.

PR in https://github.com/getAlby/lndhub.go/pull/196
