### ISSUE TITLE
Missing unit in `*_AMOUNT/BALANCE` settings

### ISSUE THREAD

**Issue by erikarvstedt** [getAlby/lndhub.go#213]
Browsing the README, I couldn't find out which unit is used in settings like `MAX_RECEIVE_AMOUNT`.
Please document this, or, even better, add the unit to the var name, like `MAX_RECEIVE_AMOUNT_SAT`.

**Comment by prusnak** [comment]
AFAIK LndHub.go uses satoshi everywhere. @bumi @kiwiidb which way do you prefer to address this issue? Should I also rename the variable names to make it obvious, or just documenting this in README is fine?

**Comment by prusnak** [comment]
Fix in https://github.com/getAlby/lndhub.go/pull/214 (which only addresses the readme file, not renaming the variables).
