### ISSUE TITLE
Make /payinvoice compatible with Zeus

### ISSUE THREAD

**Issue by kiwiidb** [getAlby/lndhub.go#223]
We are not returning the right response according to https://github.com/ZeusLN/zeus/blob/master/stores/TransactionsStore.ts#L286. The `payment_error` should be an empty string, and we are not sending anything right now.

**Comment by prusnak** [comment]
Isn't it Zeus which should be fixed? i.e replace `result.payment_error !== ''` with `!result.payment_error` to catch an empty string, null, undefined, etc.

"Fixing" this issue in LndHub.go might break clients which test for `typeof result.payment_error !== null` and we're back where we started.

Is there a spec where the correct behaviour is documented?

**Comment by bumi** [comment]
I thought about that, too. but it seems that LND is also returning an empty "" in the payment_error on successful payments. (feels wrong to me, but... )

there is no common spec for this API sadly.

**Comment by prusnak** [comment]
> it seems that LND is also returning an empty "" in the payment_error on successful payments.

Ah, OK. If that's what LND is doing, we can afford to do the same. ACK for #224

**Comment by kiwiidb** [comment]
The main clients that use the API are Bluewallet, Zeus and Alby. I've tested it with all 3 and it doesn't seem to give any problems, and now the Zeus issue is fixed. There is no real spec unfortunately, we all just use the (ugly) API that Bluewallet introduced.
