### ISSUE TITLE
Core Lightning Support

### ISSUE THREAD

**Issue by cnix-btc** [getAlby/lndhub.go#228]
Much love for Alby, great work! 👏 🐝  

I realize this is an implementation of **Lnd**Hub, so I hope this is not too much of a stupid question. Yet, referring to [this tweet](https://twitter.com/kiwiidb/status/1498341030617395202?s=20&t=nv3JWmtwu_zxeHcoCc5qMA) and [this blog post](https://blog.getalby.com/monthly-alby-buzz-lndhubgo-and-lightning/) I wanted to ask if Core Lightning support is something you guys are (still) working on.

**Comment by prusnak** [comment]
PR in https://github.com/getAlby/lndhub.go/pull/123

**Comment by cnix-btc** [comment]
Oh thanks! Sorry, should've looked through the repo more carefully.
