### ISSUE TITLE
Generate description_hash

### ISSUE THREAD

**Issue by kaikynetto** [getAlby/lndhub.go#237]
How can I generate a description_hash (or commit hash) with crypto library or otherwise in api? type in the same json, ex:

{
  "amt": 2,
"description_hash": 30292023
}

**Comment by kiwiidb** [comment]
`30292023` is not a valid SHA256 hash. But other than that, to generate an invoice with a certain description hash, you should indeed just pass in the `description_hash` as a body parameter. See https://ln.getalby.com/swagger/index.html#/Invoice/post_v2_invoices
