### ISSUE TITLE
Bun upgrade causes migrations to fail

### ISSUE THREAD

**Issue by kiwiidb** [getAlby/lndhub.go#276]
See #275 

Figure out how we can upgrade bun without breaking the migrations.

**Comment by bumi** [comment]
Looking at the docs and examples it seems they use it a bit differently: https://bun.uptrace.dev/guide/migrations.html

also in the sql files `--bun:split` is not `--migration:split`

**Comment by kiwiidb** [comment]
Updating to 1.1.10 solved the issue. See #293
