### ISSUE TITLE
Payments: logging & checks

### ISSUE THREAD

**Issue by kiwiidb** [getAlby/lndhub.go#315]
- [ ] check if invoice expired before trying to pay it
- [ ] Check if right network
- [ ] check destination is a LN pubkey
- [ ] streamline the logging & Sentry notifications - check in the code for errors that aren't really errors and don't send these to Sentry (no_route, invalid_payment_details, ...)

**Comment by reneaaron** [comment]
Can we also add some more detailed information to the keysend payments in case the wallet couldn't be found? 

It would be great to include the TLV records into the logs if no customKey / customValue was present. 
https://github.com/getAlby/lndhub.go/blob/fix/invoice-index/lib/service/invoicesubscription.go#L195
