### ISSUE TITLE
postgresql ssl disabled possible for local testing?

### ISSUE THREAD

**Issue by lujakob** [getAlby/lndhub.go#323]
Is it possible to disable ssl for postgresql connection by adding `?sslmode=disable` to the url like suggested in  https://stackoverflow.com/a/30787336/1713747 or do I need to set it up locally as explained in https://bobcares.com/blog/postgres-ssl-is-not-enabled-on-the-server/

Unfortunately I get `panic: pgdriver: sslmode 'disabled' is not supported`

Is there an easy way around this problem?

**Comment by kiwiidb** [comment]
For me, setting this environment variable just works out-of-the-box:
`DATABASE_URI=postgresql://kwinten:kwinten@localhost:5432/lndhub?sslmode=disable`

**Comment by lujakob** [comment]
My error was I had `postgres://` prefix. Now that I used `postgresql://` it works. Awesome, thanks.
