### ISSUE TITLE
Deal with poisoned messages on RabbitMQ

### ISSUE THREAD

**Issue by LucasRouckhout** [getAlby/lndhub.go#376]
A poisoned message, in our context, is a message on one of the rabbit queues that can't be successfully handled by any consumer. If the reason for these failures constitute re-queuing  the message this can lead to infinite loops by where the consumer keeps trying something that will never succeed. To avoid these situations RabitMQ allows to configure quorum queues https://www.rabbitmq.com/quorum-queues.html#poison-message-handling

Acceptance Criteria: Make sure all of our queues are quorum queues by default to avoid infinite loops of poisoned messages.

**Comment by bumi** [comment]
Is this releated to dead-letter queues? I think nacked messages should be put on a dead-letter queue from where we then can process it.

**Comment by LucasRouckhout** [comment]
Sorry for no response, got no notification of this ;)

This was actually fixed by a combination of this PR (a boy-scout rule addition was to add a delivery-limit to all queues created by lndhub) https://github.com/getAlby/lndhub.go/pull/378
And by the fact we now have a DLX queue. Both together makes sure we not only do not have infinite rejects we can also see what messages were rejected for what reason
