### ISSUE TITLE
decodeinvoice API

### ISSUE THREAD

**Issue by rolznz** [getAlby/lndhub.go#403]
Lndhub.go doesn't yet support decodeinvoice which is part of the Lndhub API spec: https://yojoe.github.io/lightninghub-api/#

**Comment by bumi** [comment]
Is this actually compatible with the new Alby decoding API. If so we could use that.

**Comment by rolznz** [comment]
API is now available here: https://guides.getalby.com/alby-wallet-api/reference/api-reference/invoices#decode-an-invoice
