### ISSUE TITLE
Add to filter for external payments

### ISSUE THREAD

**Issue by MoritzKa** [getAlby/lndhub.go#415]
Right now I cannot filter for external payments easily. We have a category called Internal but only have "true" or blank. However I can only select "true" or "false" in Metabase.
Can we introduce a label to fill the blank fields?

https://getalby.slack.com/archives/C02TDCWNX0T/p1694166401229599

**Comment by bumi** [comment]
you can filter for blank values in metabase.
I've created #417 to create defaults for those attributes.
