### ISSUE TITLE
Integers passed in a stringified JSON object to custom_records field are apparently sent by Alby as strings instead of integers

### ISSUE THREAD

**Issue by mitchdowney** [getAlby/lndhub.go#444]
I haven't witnessed this issue myself, but @johnspurlock reported it in his [matrix of app bLIP-10 TLV support](https://reflex.livewire.io/apps#issue1).

In Podverse, we are attempting to pass the feedID field as an integer within the custom_records field 7629169, but apparently the end result is a string value for feedID passed in the TLV.

Here is a sample keysend that I sent to the /payments/keysend/multi endpoint. As far as I can tell, the feedID is set to the integer `6524027` in this stringified JSON. Is this an issue I can fix on my side, or does Alby convert all integers to strings within the custom_records field?

```
[
    {
        "amount": 10,
        "destination": "03ae9f91a0cb8ff43840e3c322c4c61f019d8c1c3cea15a25cfc425ac605e61a4a",
        "custom_records": {
            "7629169": "{\"podcast\":\"Boostagram Ball\",\"feedID\":6524027,\"episode\":\"Boostagram Ball - Episode 12\",\"episode_guid\":\"c2168bc9-6063-4613-8c67-a8dedbb245d8\",\"ts\":284,\"action\":\"boost\",\"speed\":\"1\",\"pubkey\":\"podverse-pubkey\",\"value_msat_total\":1000000,\"uuid\":\"b31ef34d-97ef-4ab3-a2ec-766ba39d31b6\",\"app_name\":\"Podverse\",\"app_version\":\"4.14.3-17\",\"name\":\"Podcastindex.org\",\"sender_name\":\"Mitch D\",\"remote_feed_guid\":\"bc89b7c8-97a2-5536-8e21-d7814d3eefee\",\"remote_item_guid\":\"c61b0cf3-7e69-4350-9680-bd3ee259bedc\",\"guid\":\"6dfbd8e4-f9f3-5ea1-98a1-574134999b3b\"}",
            "7629175": "6524027"
        }
    }
]
```

**Comment by johnspurlock** [comment]
Mitch, it does not happen with all of the blips you send (most are sent with numeric feedID), only some.

An example is alby invoice with identifier `sAgLwhyFEMGznFhhQGhdSPrN` if that's helpful to debug

And the full blip info in the tlv record sent from podverse
```json
{
  "action": "boost",
  "value_msat_total": 1111000,
  "app_name": "Podverse",
  "sender_name": "Kyrin",
  "name": "reflex.livewire.io",
  "message": "I've heard the backstory many times over but I still find it inspirational. So cool that a project like this not only exists but has found the way to be self-sustaining via community support. So cool!",
  "podcast": "Podcast Answers",
  "episode": "Dave Jones: Podcast Index",
  "feedID": "6159973",
  "episode_guid": "https://podcastanswers.com/?p=414"
}
```

**Comment by mitchdowney** [comment]
@johnspurlock ah, this could be from an old version or possibly the website then. Most likely not an Alby issue. Thanks for the example! I'll close this.
