### ISSUE TITLE
Review preimage creation

### ISSUE THREAD

**Issue by bumi** [getAlby/lndhub.go#62]
does this look OK? 
https://github.com/getAlby/lndhub.go/blob/ed30a9bd8f552bef025df331e5aa23445f4c569e/lib/service/invoices.go#L321-L327

**Comment by prusnak** [comment]
The implementation has been changed to this one in the meantime and that one looks fine:

https://github.com/getAlby/lndhub.go/blob/a43779259a65b3e3a505e60a85e0e9d0e8db3023/lib/service/invoices.go#L408-L410

**Comment by bumi** [comment]
thanks for checking it!
