### ISSUE TITLE
Replace init migration to not use current models

### ISSUE THREAD

**Issue by bumi** [getAlby/lndhub.go#71]
Currently the init migration is dynamic and creates tables based on the current model configuration.
This makes future migrations a bit tricky. 
We should have one fixed initial migration and not use the current models for that. 
Maybe we simply use SQL migrations?

**Comment by skosito** [comment]
Hey @bumi , this one is next unassigned issue in list. Could you please assign it to me, or give me permission to do it? Thanks!
