### ISSUE TITLE
Custom usernames

### ISSUE THREAD

**Issue by AaronDewes** [getAlby/lndhub.go#73]
Instead of a randomly assigned username, an user should have the ability to choose an username (This should be optional to keep API compatibility) and maybe even password (So users can completely choose their own login credentials).

A custom username would make stuff like Lightning addresses or even tipping pages similar to LnMe easily possible inside LNDHub (a donation page as an outside wrapper, but it could still use lndhub's usernames).

The downside of this is that a server admin could then more easily identify their users on other platforms (If I make an account AaronDewes, you know it's me, but if my account has a random name only I know, you can't easily track me specifically)

**Comment by bumi** [comment]
This basically means that the CreateUser function should accept a custom `login` and `password` instead of the created one here: https://github.com/getAlby/lndhub.go/blob/main/lib/service/user.go#L13-L19
if no login or password is provided we default to the current behavior and use that `randStringBytes(20)`

Here is the request for `/create` https://github.com/getAlby/lndhub.go/blob/main/controllers/create.ctrl.go#L27

**Comment by skosito** [comment]
Hey @bumi , this one is next unassigned issue in list. Could you please assign it to me, or give me permission to do it? Thanks!

**Comment by kiwiidb** [comment]
I'll post my comments from the PR here as well. These are mainly relevant for a user-provided password, in the context of the Alby wallet. So they don't really apply to the username part, which I think is a good idea. What would be the main benefits of letting the users choosing their passwords?
```
I don't know if we actually need this, as it is not part of the LNDHub API.
If users create their wallet through Bluewallet, this won't be used.
If users create their wallet through the browser extension or through the Alby web app, we can implement this.

But do we really want to let users do this? We'd need to check if the password is strong enough. If they create the password inside the extension, I don't know how well password manager extensions will be able to interact with this? And will users actually be interested in this? After all, the best protection against a lost account would be that they simply import the browser wallet into Bluewallet, so they will always have a recovery mechanism in case of losing one device.
```
