### ISSUE TITLE
Unauthorized API calls to generate invoices

### ISSUE THREAD

**Issue by godSaysHODL** [getAlby/lndhub.go#74]
I think it would be fantastic to be able to query LNDhub with an account# (or custom username if that is implemented) in order to create an invoice in their wallet, without requiring account password.

The reason being, is to implement cool web apps similar to how plebpay.com uses the Strike api to make a lightning invoice for the wallet of a Strike user. https://github.com/SamSamskies/PlebPay 

It would also enable tipping functionality, or a friends list inside of wallets where you could tip people you know who are on Bluewallet, GetAlby, or their own Self hosted LNDhub. This would bring a functionality very similar to LNaddresses, but easily hosted on top of node implementations that already have LNDhub, like myNodeBTC, Umbrel, RaspiBlitz.

EDIT: some more technical requirements:

POST `/invoice/<user_login>`
No Authorization header required.
parameters: the same as the current `/addinvoice` call
```
type AddInvoiceRequestBody struct {
	Amount          interface{} `json:"amt"` // amount in Satoshi
	Memo            string      `json:"memo"`
	DescriptionHash string      `json:"description_hash" validate:"omitempty,hexadecimal,len=64"`
}
```
This is not yet native LN Address support, but it does make serving an LN Address powered by an lndhub account very easy, you could do it using a very simple serverless function.

**Comment by kiwiidb** [comment]
@bumi this would also be useful for the Alby LN Address service. That way the Rails app doesn't need to store user credentials.
