### ISSUE TITLE
Dynamic LND fee limits

### ISSUE THREAD

**Issue by bumi** [getAlby/lndhub.go#81]
We need to set dynamic LND fee limits depending on the amount we send:

if the `invoice.Amount` <= 1000 we use a fixed fee limit: `10` (?)
if the amount is > 1000 we calculate:
`math.Ceil(invoice.Amount * 0.01) + 1` similar to what lndhub currently does.

And we should check if those can be combined? e.g. have a max fee limit and a percentage one. Whatever is smaller is then used.

**Comment by skosito** [comment]
@bumi @kiwiidb just one question, is this logic supposed to replace?
```
invoice.Fee = paymentResponse.PaymentRoute.TotalFees
```

**Comment by kiwiidb** [comment]
That is how we get the actual fees after the payment has completed.
The fee limits beforehand are set here: https://github.com/getAlby/lndhub.go/blob/feature/keysend-custom-records/lib/service/invoices.go#L137-L138
