### ISSUE TITLE
Create a logo :)

### ISSUE THREAD

**Issue by bumi** [getAlby/lndhub.go#88]

**Comment by stefanwuest** [comment]
I gave it a go. Happy to make a PR and add it to the README + share the files in a separate repo.
![LNHub go](https://user-images.githubusercontent.com/5959858/163722235-fb6be0f5-622e-4bdb-8332-b2799c95cd59.png)

**Comment by bumi** [comment]
whoot! that is super cool! nice @kiwiidb what do you think? 

in the future we can alos drop the `D` at some point when other backends are supported and use LNHub.go :)

**Comment by bumi** [comment]
LN(D)Hub now LNHub later :D lol

**Comment by kiwiidb** [comment]
@stefanwuest could you create a PR to add the logo to the README?
