### ISSUE TITLE
Remove unnecessary dependencies

### ISSUE THREAD

**Issue by kiwiidb** [getAlby/lndhub.go#96]
I believe the following dependencies should be removed:
 
- https://github.com/lightningnetwork/lnd/zpay32. This dependency is currently used to decode bolt11 invoices. I think it's a better idea to use the Lightning node back-end to decode invoices that returns a simple struct defined in the lnd package.
- https://github.com/btcsuite/btcd/btcec. This dependency is used to get the back-end node's public key. I think it's simpler if we just stored this as a string.
- https://github.com/btcsuite/btcd/chaincfg. Dependency of the zpay32 package.

I think these changes should help us when we implement a second node back-end.

**Comment by bumi** [comment]
so much less code now also :) 👍
