### ISSUE TITLE
Handling of in transit payments

### ISSUE THREAD

**Issue by kiwiidb** [getAlby/lndhub.go#97]
Currently, we just call "SendpaymentSync" and depending on the result

- mark the payment as completed and complete the database transaction
- rollback the database transaction in case of an error

However, it might be possible that the call returns an "in transit" state of the payment. In this case, it is possible that the transaction is completed later. We should investigate if this is possible and if so, account for these kind of payments.

Another possible bug might be when a second request to make a payment comes in while the first is still pending. Does the database lock prevent this from happening, or is this possible? If it is possible, the pending amount should not be accounted in the user's total balance.

A possible solution might be to commit pending payments in the database, and update them once we are sure they either succeeded or failed. At startup time, we can check the status of all pending payments in the database against the Lightning node (reconciliation).

**Comment by kiwiidb** [comment]
Cfr. LNDHub does this asynchronously: https://github.com/BlueWallet/LndHub/blob/master/controllers/api.js#L305

**Comment by bumi** [comment]
True, we probably should not rollback but directly commit each DB transaction. This makes sure the funds are moved from the current account to the outgoing account. 
On error we can then move the funds back from the outgoing account to the current account and mark the invoice as errored. 

but it might be hard to get an "on error" event and only get a settled event? do you know that?
