### ISSUE TITLE
Prevent direct push to main

### ISSUE THREAD

**Issue by skosito** [getAlby/lndhub.go#99]
I think it would be a good idea to prevent push to main, it happened accidentally to me tonight, I reverted it, but I think it would be good to have this constraint in place.

**Comment by bumi** [comment]
👍 yeah +1

**Comment by kiwiidb** [comment]
I've updated the settings and confirmed them.
![Schermafbeelding 2022-02-10 om 10 34 18](https://user-images.githubusercontent.com/33457577/153378979-111c1b59-3482-4fd3-83d1-27286bcd5406.png)
![Schermafbeelding 2022-02-10 om 10 34 37](https://user-images.githubusercontent.com/33457577/153379019-d1518044-05ee-43ef-b840-c7da60933e9a.png)
